import type { TSentence } from "~/types";

export const Sentences: TSentence = {
  beginner: [
    "The cat sat on the mat.",
    "I like to eat apples and bananas.",
    "The sun is shining brightly today.",
    "She walks her dog every morning.",
    "They play soccer in the park.",
    "He drinks coffee with milk.",
    "We went to the beach last weekend.",
    "The children are playing in the garden.",
    "I enjoy reading books in my free time.",
    "The car is parked in the garage.",
    "She sings in the shower every day.",
    "They cook dinner together on Sundays.",
    "He works at a local supermarket.",
    "We watched a movie last night.",
    "The flowers in the vase are beautiful.",
    "I brush my teeth twice a day.",
    "They visit their grandparents once a month.",
    "He rides his bike to work.",
    "We had pizza for lunch today.",
    "The dog chased the ball across the yard.",
  ],
  intermediate: [
    "The professor explained the complex theory to his students.",
    "She's considering a career change to pursue her passion.",
    "The company's quarterly report showed significant growth.",
    "They're planning an expedition to climb Mount Everest.",
    "The chef created a fusion dish combining Italian and Japanese cuisines.",
    "The museum's new exhibit features ancient artifacts from Egypt.",
    "He's learning to play the piano and compose his own music.",
    "The scientists are researching renewable energy sources.",
    "She's writing a novel based on her experiences traveling abroad.",
    "The city council is debating a new public transportation plan.",
    "They're developing an app to help people manage their finances.",
    "The documentary explores the effects of climate change on wildlife.",
    "He's studying marine biology and plans to work in ocean conservation.",
    "The artist's latest sculpture combines various recycled materials.",
    "She's training for a marathon to raise money for charity.",
    "The company is implementing a new customer service strategy.",
    "They're renovating an old building to create affordable housing.",
    "He's researching the history of cryptography and its modern applications.",
    "The orchestra is preparing for its international tour next month.",
    "She's designing a sustainable fashion line using eco-friendly materials.",
  ],
  advanced: [
    "The quantum physicist's groundbreaking research challenges our understanding of particle behavior.",
    "The diplomat negotiated a complex international treaty to address global climate change.",
    "The neuroscientist's study on brain plasticity has implications for treating cognitive disorders.",
    "The cybersecurity expert developed an algorithm to detect and prevent sophisticated hacking attempts.",
    "The economist's analysis of market trends predicts a shift towards sustainable industries.",
    "The anthropologist's fieldwork reveals new insights into ancient Mayan social structures.",
    "The bioengineer are experimenting with CRISPR technology to cure genetic diseases.",
    "The philosopher's treatise on ethics in artificial intelligence sparked widespread debate.",
    "The astrophysicist's theory about dark matter challenges the standard model of particle physics.",
    "The linguist's research on endangered languages contributes to preserving cultural heritage.",
    "The constitutional lawyer argued a landmark case before the Supreme Court.",
    "The epidemiologist's model accurately predicted the spread of the pandemic.",
    "The marine biologist's discovery of a new deep-sea species has ecological implications.",
    "The quantum computing researcher achieved a breakthrough in error correction algorithms.",
    "The psychologist's longitudinal study on childhood development spans three decades.",
    "The environmental engineer designed an innovative system for large-scale water purification.",
    "The geopolitical analyst's assessment of global power dynamics influences foreign policy.",
    "The nanotechnologies invention could revolutionize drug delivery systems.",
    "The cognitive scientist's research on artificial neural networks mimics human learning processes.",
    "The theoretical physicist's work on string theory aims to unify quantum mechanics and general relativity.",
  ],

  expert: [
    "The interdisciplinary research team, comprising quantum physicists, computer scientists, and mathematicians, has made a breakthrough in quantum error correction, potentially paving the way for the development of large-scale, fault-tolerant quantum computers that could revolutionize fields such as cryptography, drug discovery, and climate modeling.",
    "In a groundbreaking paper published in a leading scientific journal, the team of astrophysicists presents compelling evidence for a novel theory of dark matter that reconciles previously conflicting observations and could potentially solve one of the most persistent mysteries in modern cosmology, challenging our fundamental understanding of the universe's composition and evolution.",
    "The renowned philosopher's latest treatise on the ethics of artificial intelligence and machine consciousness delves into the intricate relationships between human cognition, technological advancement, and moral responsibility, raising profound questions about the nature of consciousness, free will, and the potential rights of sentient machines in a rapidly evolving technological landscape.",
    "A comprehensive meta-analysis of climate change studies conducted over the past three decades reveals alarming trends in global temperature rise, sea level increase, and extreme weather events, underscoring the urgent need for coordinated international efforts to implement aggressive carbon reduction strategies and adapt to the inevitable consequences of a changing climate.",
    "The linguistic anthropologist's extensive fieldwork among indigenous communities in remote regions has uncovered fascinating insights into the complex interplay between language, culture, and cognitive processes, shedding new light on the Sapir-Whorf hypothesis and contributing to our understanding of linguistic diversity and its role in shaping human perception and thought.",
  ],
};
